version: '{build}'

os: Windows Server 2016
image: Visual Studio 2017

platform:
  - x64

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk12
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: SET PATH=%PATH%;%JAVA_HOME%\bin
  - cmd: SET PATH=%PATH%;%PROGRAMFILES(X86)%\sbt\bin
  - cmd: choco install sbt
  - cmd: sbt version & exit 0

build_script:
  - sbt +test:compile +it:compile

test_script:
  - sbt +test

cache:
  - '%LOCALAPPDATA%\Coursier\Cache -> **\dependencies.sbt, project\*'
  - '%USERPROFILE%\.ivy2 -> **\dependencies.sbt, project\*'
  - '%USERPROFILE%\.sbt -> **\dependencies.sbt, project\*'
