language: scala

matrix:
  include:
    - os: linux
    - osx
      osx_image: xcode9.3

jdk:
  - openjdk8
  - openjdk11

script:
  - sbt '+test'

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ivy2
    - $HOME/.sbt