language: scala

os:
  - linux
  - osx

jdk:
  - openjdk8
  - openjdk11

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      jdk: openjdk8
  exclude:
    - os: osx
      jdk: openjdk8

script:
  - sbt "+test"

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ivy2
    - $HOME/.sbt