language: scala

addons:
  apt:
    packages:
      - expect-dev

jdk:
  - openjdk8

script:
  - unbuffer sbt '+test'
  - unbuffer sbt '+it:test'

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ivy2
    - $HOME/.sbt