language: scala

matrix:
  include:
    - os: linux
      jdk:
        - openjdk8
        - openjdk11
    - os: osx
      osx_image: xcode9.3
      jdk:
        - openjdk8


script:
  - sbt "+test"

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ivy2
    - $HOME/.sbt